version: "3.8"
services:
  database-prod:
    image: "postgres"
    container_name: database-prod
    ports:
      - "5434:5434"
    volumes:
      - "db_data_prod:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest-cafe-db-prod
      - PGPORT=5434
  backend:
    container_name: nest-cafe-api-backend
    build:
      target: prod
      context: ./nest-cafe
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - HOST=http://127.0.0.1:5000
      - DB_TYPE=postgres # postgres, mysql, sqlite...
      - DB_NAME=nest-cafe-db-prod # database name
      - DB_HOST=database-prod # database host
      - DB_PORT=5434 # database port
      - DB_USER=postgres # username you set when installing db
      - DB_PASSWORD=root # password for user
    ports:
      - "5000:5000"
    depends_on:
      - database-prod
volumes:
  db_data_prod:
